"""empty message

Revision ID: 2b7fbadd6a93
Revises: f7fc72462c39
Create Date: 2023-05-02 10:19:01.293223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b7fbadd6a93'
down_revision = 'f7fc72462c39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pokemon_cards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('card_type', sa.String(), nullable=False))
        batch_op.drop_column('type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pokemon_cards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.VARCHAR(), nullable=False))
        batch_op.drop_column('card_type')

    # ### end Alembic commands ###
